### ISSUE TITLE
Spy rules prevent 'Your Phone' application from working.

### ISSUE THREAD

**Issue by Wicloz** [crazy-max/WindowsSpyBlocker#300]
### Behaviour

When solely using the spy rules, it is not possible to add new devices in the 'Your Phone' app. This block should be moved to the extra rules. `continuum.dds.microsoft.com` has been identified as the offending rule.

A Source: https://www.reddit.com/r/pihole/comments/drylpk/pihole_and_your_phone_companion_app_microsoft/
This has been tested and indeed works.

#### Steps to reproduce this issue

1. Activate a variant of the spy rule set.
2. Install the 'Your Phone' app on your PC and phone.
3. Attempt to connect a new device.

#### Expected behaviour

The device setup completes successfully.

#### Actual behaviour

A warning is given during the setup. Continuing simply causes the setup to never complete.

### Rules used

`data/hosts/spy.txt`

### Configuration

Rules are applied by converting them into an appropriate Unbound configuration file, which is setup as the default DNS server for the network. Blocks are otherwise applied as expected.

**Comment by crazy-max** [comment]
@Wicloz Will be moved in the next release after seeing legit connections in my logs recently.

> Rules are applied by converting them into an appropriate Unbound configuration file

Would you mind sharing your Unbound config? Maybe it could fit here as another [provider](https://crazymax.dev/WindowsSpyBlocker/blocking-rules/#providers)?

**Comment by Wicloz** [comment]
> Would you mind sharing your Unbound config? Maybe it could fit here as another provider?

Sure. Sending the entire config would be pointless since it is build from multiple sources but this should give an idea for the syntax:
```
server:
  local-zone: "no-tv2.cdn.videoplaza.tv" static
  local-zone: "portalwojewodzki.098.pl" static
  local-zone: "consent.emiawards.cotswoldlife.co.uk" static
  local-zone: "web5895.affex.org" static
  local-zone: "0.0.0.0refreshnerer27rb.info" static
  local-zone: "exmuo.org" static
  local-zone: "huhughyaw.com" static
  local-zone: "b.i48.affex.org" static
  local-zone: "svc-cer.linkury.com" static
```

This is written using the following code block:
```
with open('/etc/unbound/unbound.conf.d/blocklist.conf', 'w') as fp:
    fp.write('server:\n')
    for block in blocks:
        fp.write(f'  local-zone: "{block}" static\n')
```
Where `blocks` is an iterable of subdomains/domains.
